[View in Colaboratory](https://colab.research.google.com/github/DeepankJain/Asssignment/blob/master/NaiveBayes.ipynb)

In [0]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sb
from fractions import Fraction
%matplotlib inline
from sklearn.datasets import load_iris

In [2]:
space=14

p_sunny=5/14
p_play=9/14
p_play_intersection_s=3/14
p_playIsunny='%.3f'%(p_play_intersection_s/p_sunny )
print("Probability of Playing when sunny is ",Fraction(p_playIsunny))

Probability of Playing when sunny is  3/5


In [3]:
iris=load_iris()

print(iris.data)
print(iris.target)
d=iris.data
t=iris.target

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [0]:
from sklearn.model_selection import train_test_split as  ttl
train_x,test_x,train_y,test_y=ttl(d,t,test_size=0.2)

In [5]:
from sklearn.naive_bayes import GaussianNB
model_GNB=GaussianNB()

model_GNB.fit(train_x,train_y)

GaussianNB(priors=None)

In [0]:
prediction_GNB=model_GNB.predict(test_x)

In [7]:
results_GNB=pd.DataFrame({'Prediction':prediction_GNB,'Actual':test_y})
print(results_GNB)

    Actual  Prediction
0        1           1
1        0           0
2        1           1
3        1           1
4        2           2
5        1           1
6        1           1
7        1           1
8        2           2
9        1           1
10       0           0
11       0           0
12       0           0
13       0           0
14       1           1
15       1           1
16       1           1
17       0           0
18       1           1
19       0           0
20       1           1
21       2           2
22       2           2
23       0           0
24       0           0
25       0           0
26       1           1
27       1           1
28       1           1
29       0           0


In [8]:
from sklearn.naive_bayes import MultinomialNB
model_MNB=MultinomialNB()

model_MNB.fit(train_x,train_y)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [0]:
prediction_MNB=model_MNB.predict(test_x)

In [11]:
results_MNB=pd.DataFrame({'Prediction':prediction_MNB,'Actual':test_y})
print(results_MNB)

    Actual  Prediction
0        1           2
1        0           0
2        1           2
3        1           2
4        2           2
5        1           2
6        1           2
7        1           2
8        2           2
9        1           2
10       0           0
11       0           0
12       0           0
13       0           0
14       1           2
15       1           2
16       1           2
17       0           0
18       1           2
19       0           0
20       1           2
21       2           2
22       2           2
23       0           0
24       0           0
25       0           0
26       1           2
27       1           2
28       1           2
29       0           0


In [0]:
from sklearn.metrics import r2_score,confusion_matrix,classification_report

In [13]:
print(confusion_matrix(test_y,prediction_GNB))

[[11  0  0]
 [ 0 15  0]
 [ 0  0  4]]


In [14]:
print(r2_score(test_y, prediction_GNB))

1.0


In [15]:
print(classification_report(test_y, prediction_GNB))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        11
          1       1.00      1.00      1.00        15
          2       1.00      1.00      1.00         4

avg / total       1.00      1.00      1.00        30



In [16]:
print(confusion_matrix(test_y,prediction_MNB))

[[11  0  0]
 [ 0  0 15]
 [ 0  0  4]]


In [17]:
print(r2_score(test_y, prediction_MNB))

-0.12219451371571077


In [18]:
print(r2_score(test_y, prediction_MNB))

-0.12219451371571077
